name: Cargo Build & Test

on:
  pull_request:
    branches: 
      - main
env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./quoridor4all/src-tauri/
    steps:
      - uses: actions/checkout@v4
      - name: Tauri dependencies
        run: >-
          sudo apt-get update &&
          sudo apt-get install -y
          libgtk-3-dev
          libayatana-appindicator3-dev
          libwebkit2gtk-4.0-dev
          webkit2gtk-driver
          xvfb
      - run: rustup update stable && rustup default stable
      - run: cargo build
      - run: cargo test
